version: '3.8'

services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/dormstart
      REDIS_URL: redis://redis:6379
      PORT: 5000
      NODE_ENV: development
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./BE:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo_data:
